#point to the path of the simics installation that contains magic-instruction.h
#it's included in simics_installation_directory/src/include/simics/
sort_magic.o: sort_magic.cpp
	g++ sort_magic.cpp -lstdc++ -o sort_magic.o
clean: 
	rm sort_magic.o
