#                                                              -*- Makefile -*-
# Simics module makefile
#

MODULE_COMPONENTS := pci_capture_comp

SIMICS_API := latest
THREAD_SAFE:=yes
PYTHON_FILES = pci_capture_comp.py module_load.py

include $(MODULE_MAKEFILE)
