#                                                              -*- Makefile -*-
# Simics module makefile
#

SIMICS_API := 6
THREAD_SAFE:=yes
MODULE_CLASSES = pci_data_capture

SRC_FILES= pci-data-capture.dml
PYTHON_FILES := module_load.py

EXTRA_MODULE_VPATH += dml-lib

include $(MODULE_MAKEFILE)
